import type { PimModelGroup } from "./pim-types";

export const pimModelSeed: PimModelGroup[] = [
  {
    id: "base",
    name: "Base",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.14, equity: 0.83, alternatives: 0.03 },
      allEquity: { cash: 0.0, fixedIncome: 0.0, equity: 1.0, alternatives: 0.0 },
    },
    cadSplit: 0.5,
    usdSplit: 0.5,
    holdings: [
      { name: "JP MORGAN US BOND ACTIVE ETF", symbol: "JBND-T", currency: "CAD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "RBC US CORE PLUS BOND POOL", symbol: "RBF1083", currency: "USD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "ALPHABET", symbol: "GOOGL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "AMAZON", symbol: "AMZN", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CANADIAN NATIONAL RAILWAY", symbol: "CNR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CELESTICA", symbol: "CLS-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CONSTELLATION SOFTWARE", symbol: "CSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ECHOSTAR", symbol: "SATS", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FIDELITY GLOBAL INNOVATORS CLASS SERIES F", symbol: "FID5982-T", currency: "CAD", assetClass: "equity", weightInClass: 0.068182 },
      { name: "FUNDSTRAT GRANNY SHOTS US SMALL & MID-CAP ETF", symbol: "GRNJ", currency: "USD", assetClass: "equity", weightInClass: 0.05 },
      { name: "GE VERNOVA", symbol: "GEV", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ISHARES CORE S&P 500 INDEX ETF (CAD-HEDGED)", symbol: "XSP-T", currency: "CAD", assetClass: "equity", weightInClass: 0.083333 },
      { name: "ISHARES CORE S&P 500 INDEX ETF USD", symbol: "XUS.U", currency: "USD", assetClass: "equity", weightInClass: 0.143939 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF (CAD-HEDGED)", symbol: "XUH-T", currency: "CAD", assetClass: "equity", weightInClass: 0.166667 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF USD", symbol: "XUU.U", currency: "USD", assetClass: "equity", weightInClass: 0.106061 },
      { name: "ISHARES US SMALL CAP INDEX ETF (CAD-HEDGED)", symbol: "XSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "JPMORGAN CHASE", symbol: "JPM", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NORTHLAND POWER", symbol: "NPI-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NUTRIEN", symbol: "NTR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ONEOK", symbol: "OKE", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "QUANTA SERVICES", symbol: "PWR", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TESLA", symbol: "TSLA", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TEXAS PACIFIC LAND", symbol: "TPL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TOURMALINE OIL", symbol: "TOU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "UBER", symbol: "UBER", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "US BANCORP", symbol: "USB", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "DYNAMIC PREMIUM YIELD PLUS", symbol: "DYN3361-T", currency: "CAD", assetClass: "alternative", weightInClass: 0.5 },
      { name: "DYNAMIC PREMIUM YIELD PLUS USD", symbol: "DYN3366", currency: "USD", assetClass: "alternative", weightInClass: 0.5 },
    ],
  },
  {
    id: "pc-usa",
    name: "PC USA",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.14, equity: 0.83, alternatives: 0.03 },
      allEquity: { cash: 0.0, fixedIncome: 0.0, equity: 1.0, alternatives: 0.0 },
    },
    cadSplit: 0.084,
    usdSplit: 0.916,
    holdings: [
      { name: "JPMORGAN ACTIVE BOND ETF", symbol: "JBND", currency: "USD", assetClass: "fixedIncome", weightInClass: 1.0 },
      { name: "ALPHABET", symbol: "GOOGL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "AMAZON", symbol: "AMZN", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CANADIAN NATIONAL RAILWAY", symbol: "CNR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CELESTICA", symbol: "CLS-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CONSTELLATION SOFTWARE", symbol: "CSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ECHOSTAR", symbol: "SATS", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FUNDSTRAT GRANNY SHOTS US SMALL & MID-CAP ETF", symbol: "GRNJ", currency: "USD", assetClass: "equity", weightInClass: 0.05 },
      { name: "GE VERNOVA", symbol: "GEV", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ISHARES CORE S&P TOTAL US STOCK MARKET ETF", symbol: "ITOT", currency: "USD", assetClass: "equity", weightInClass: 0.568182 },
      { name: "JPMORGAN CHASE", symbol: "JPM", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NORTHLAND POWER", symbol: "NPI-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NUTRIEN", symbol: "NTR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ONEOK", symbol: "OKE", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "QUANTA SERVICES", symbol: "PWR", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TESLA", symbol: "TSLA", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TEXAS PACIFIC LAND", symbol: "TPL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TOURMALINE OIL", symbol: "TOU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "UBER", symbol: "UBER", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "US BANCORP", symbol: "USB", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "VANGUARD RUSSELL 2000 ETF", symbol: "VTWO", currency: "USD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "WISDOMTREE EQUITY PREMIUM INCOME", symbol: "WTPI", currency: "USD", assetClass: "alternative", weightInClass: 1.0 },
    ],
  },
  {
    id: "non-res",
    name: "Non-Res",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.14, equity: 0.83, alternatives: 0.03 },
      allEquity: { cash: 0.0, fixedIncome: 0.0, equity: 1.0, alternatives: 0.0 },
    },
    cadSplit: 0.5,
    usdSplit: 0.5,
    holdings: [
      { name: "JP MORGAN US BOND ACTIVE ETF", symbol: "JBND-T", currency: "CAD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "JPMORGAN ACTIVE BOND ETF", symbol: "JBND", currency: "USD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "ALPHABET", symbol: "GOOGL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "AMAZON", symbol: "AMZN", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CANADIAN NATIONAL RAILWAY", symbol: "CNR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CELESTICA", symbol: "CLS-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CONSTELLATION SOFTWARE", symbol: "CSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ECHOSTAR", symbol: "SATS", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FIDELITY GLOBAL INNOVATORS ETF", symbol: "FINN-T", currency: "CAD", assetClass: "equity", weightInClass: 0.068182 },
      { name: "FUNDSTRAT GRANNY SHOTS US SMALL & MID-CAP ETF", symbol: "GRNJ", currency: "USD", assetClass: "equity", weightInClass: 0.05 },
      { name: "GE VERNOVA", symbol: "GEV", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ISHARES CORE S&P 500 INDEX ETF (CAD-HEDGED)", symbol: "XSP-T", currency: "CAD", assetClass: "equity", weightInClass: 0.083333 },
      { name: "ISHARES CORE S&P 500 INDEX ETF USD", symbol: "XUS.U", currency: "USD", assetClass: "equity", weightInClass: 0.143939 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF (CAD-HEDGED)", symbol: "XUH-T", currency: "CAD", assetClass: "equity", weightInClass: 0.166667 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF USD", symbol: "XUU.U", currency: "USD", assetClass: "equity", weightInClass: 0.106061 },
      { name: "ISHARES US SMALL CAP INDEX ETF (CAD-HEDGED)", symbol: "XSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "JPMORGAN CHASE", symbol: "JPM", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NORTHLAND POWER", symbol: "NPI-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NUTRIEN", symbol: "NTR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ONEOK", symbol: "OKE", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "QUANTA SERVICES", symbol: "PWR", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TESLA", symbol: "TSLA", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TEXAS PACIFIC LAND", symbol: "TPL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TOURMALINE OIL", symbol: "TOU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "UBER", symbol: "UBER", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "US BANCORP", symbol: "USB", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "PURPOSE ENHANCED PREMIUM YIELD", symbol: "PAYF-T", currency: "CAD", assetClass: "alternative", weightInClass: 0.5 },
      { name: "WISDOMTREE EQUITY PREMIUM INCOME", symbol: "WTPI", currency: "USD", assetClass: "alternative", weightInClass: 0.5 },
    ],
  },
  {
    id: "no-us-situs",
    name: "No US Situs",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.14, equity: 0.83, alternatives: 0.03 },
      allEquity: { cash: 0.0, fixedIncome: 0.0, equity: 1.0, alternatives: 0.0 },
    },
    cadSplit: 0.5,
    usdSplit: 0.5,
    holdings: [
      { name: "JP MORGAN US BOND ACTIVE ETF", symbol: "JBND-T", currency: "CAD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "RBC US CORE PLUS BOND POOL", symbol: "RBF1083", currency: "USD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CANADIAN NATIONAL RAILWAY", symbol: "CNR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CELESTICA", symbol: "CLS-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CONSTELLATION SOFTWARE", symbol: "CSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "DYNAMIC POWER AMERICAN GROWTH", symbol: "DYN439", currency: "USD", assetClass: "equity", weightInClass: 0.05 },
      { name: "FIDELITY GLOBAL INNOVATORS CLASS SERIES F", symbol: "FID5982-T", currency: "CAD", assetClass: "equity", weightInClass: 0.068182 },
      { name: "ISHARES CORE S&P 500 INDEX ETF (CAD-HEDGED)", symbol: "XSP-T", currency: "CAD", assetClass: "equity", weightInClass: 0.083333 },
      { name: "ISHARES CORE S&P 500 INDEX ETF USD", symbol: "XUS.U", currency: "USD", assetClass: "equity", weightInClass: 0.243939 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF (CAD-HEDGED)", symbol: "XUH-T", currency: "CAD", assetClass: "equity", weightInClass: 0.166667 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF USD", symbol: "XUU.U", currency: "USD", assetClass: "equity", weightInClass: 0.206061 },
      { name: "ISHARES US SMALL CAP INDEX ETF (CAD-HEDGED)", symbol: "XSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "NORTHLAND POWER", symbol: "NPI-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NUTRIEN", symbol: "NTR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TOURMALINE OIL", symbol: "TOU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "DYNAMIC PREMIUM YIELD PLUS", symbol: "DYN3262-T", currency: "CAD", assetClass: "alternative", weightInClass: 0.5 },
      { name: "DYNAMIC PREMIUM YIELD PLUS USD", symbol: "DYN3265", currency: "USD", assetClass: "alternative", weightInClass: 0.5 },
    ],
  },
  {
    id: "cgf",
    name: "CGF",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.2, equity: 0.77, alternatives: 0.03 },
    },
    cadSplit: 0.5,
    usdSplit: 0.5,
    holdings: [
      { name: "JP MORGAN US BOND ACTIVE ETF", symbol: "JBND-T", currency: "CAD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "RBC US CORE PLUS BOND POOL", symbol: "RBF1083", currency: "USD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "ALPHABET", symbol: "GOOGL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "AMAZON", symbol: "AMZN", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CANADIAN NATIONAL RAILWAY", symbol: "CNR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CELESTICA", symbol: "CLS-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CONSTELLATION SOFTWARE", symbol: "CSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ECHOSTAR", symbol: "SATS", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FIDELITY GLOBAL INNOVATORS CLASS SERIES F", symbol: "FID5982-T", currency: "CAD", assetClass: "equity", weightInClass: 0.068182 },
      { name: "FUNDSTRAT GRANNY SHOTS US SMALL & MID-CAP ETF", symbol: "GRNJ", currency: "USD", assetClass: "equity", weightInClass: 0.05 },
      { name: "GE VERNOVA", symbol: "GEV", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ISHARES CORE S&P 500 INDEX ETF (CAD-HEDGED)", symbol: "XSP-T", currency: "CAD", assetClass: "equity", weightInClass: 0.083333 },
      { name: "ISHARES CORE S&P 500 INDEX ETF USD", symbol: "XUS.U", currency: "USD", assetClass: "equity", weightInClass: 0.143939 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF (CAD-HEDGED)", symbol: "XUH-T", currency: "CAD", assetClass: "equity", weightInClass: 0.166667 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF USD", symbol: "XUU.U", currency: "USD", assetClass: "equity", weightInClass: 0.106061 },
      { name: "ISHARES US SMALL CAP INDEX ETF (CAD-HEDGED)", symbol: "XSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "JPMORGAN CHASE", symbol: "JPM", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NORTHLAND POWER", symbol: "NPI-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NUTRIEN", symbol: "NTR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ONEOK", symbol: "OKE", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "QUANTA SERVICES", symbol: "PWR", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TESLA", symbol: "TSLA", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TEXAS PACIFIC LAND", symbol: "TPL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TOURMALINE OIL", symbol: "TOU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "UBER", symbol: "UBER", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "US BANCORP", symbol: "USB", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "DYNAMIC PREMIUM YIELD PLUS", symbol: "DYN3361-T", currency: "CAD", assetClass: "alternative", weightInClass: 0.5 },
      { name: "DYNAMIC PREMIUM YIELD PLUS USD", symbol: "DYN3366", currency: "USD", assetClass: "alternative", weightInClass: 0.5 },
    ],
  },
  {
    id: "ey",
    name: "EY",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.14, equity: 0.83, alternatives: 0.03 },
      allEquity: { cash: 0.0, fixedIncome: 0.0, equity: 1.0, alternatives: 0.0 },
    },
    cadSplit: 0.5,
    usdSplit: 0.5,
    holdings: [
      { name: "JP MORGAN US BOND ACTIVE ETF", symbol: "JBND-T", currency: "CAD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "RBC US CORE PLUS BOND POOL", symbol: "RBF1083", currency: "USD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CANADIAN NATIONAL RAILWAY", symbol: "CNR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CELESTICA", symbol: "CLS-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CONSTELLATION SOFTWARE", symbol: "CSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FUNDSTRAT GRANNY SHOTS US SMALL & MID-CAP ETF", symbol: "GRNJ", currency: "USD", assetClass: "equity", weightInClass: 0.05 },
      { name: "ECHOSTAR", symbol: "SATS", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FIDELITY GLOBAL INNOVATORS CLASS SERIES F", symbol: "FID5982-T", currency: "CAD", assetClass: "equity", weightInClass: 0.068182 },
      { name: "GE VERNOVA", symbol: "GEV", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ISHARES CORE S&P 500 INDEX ETF (CAD-HEDGED)", symbol: "XSP-T", currency: "CAD", assetClass: "equity", weightInClass: 0.092424 },
      { name: "ISHARES CORE S&P 500 INDEX ETF USD", symbol: "XUS.U", currency: "USD", assetClass: "equity", weightInClass: 0.171212 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF (CAD-HEDGED)", symbol: "XUH-T", currency: "CAD", assetClass: "equity", weightInClass: 0.175758 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF USD", symbol: "XUU.U", currency: "USD", assetClass: "equity", weightInClass: 0.133333 },
      { name: "ISHARES US SMALL CAP INDEX ETF (CAD-HEDGED)", symbol: "XSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "JPMORGAN CHASE", symbol: "JPM", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NUTRIEN", symbol: "NTR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ONEOK", symbol: "OKE", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "QUANTA SERVICES", symbol: "PWR", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TESLA", symbol: "TSLA", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TEXAS PACIFIC LAND", symbol: "TPL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TOURMALINE OIL", symbol: "TOU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "UBER", symbol: "UBER", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "DYNAMIC PREMIUM YIELD PLUS", symbol: "DYN3361-T", currency: "CAD", assetClass: "alternative", weightInClass: 0.5 },
      { name: "DYNAMIC PREMIUM YIELD PLUS USD", symbol: "DYN3366", currency: "USD", assetClass: "alternative", weightInClass: 0.5 },
    ],
  },
  {
    id: "kpmg",
    name: "KPMG",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.14, equity: 0.83, alternatives: 0.03 },
      allEquity: { cash: 0.0, fixedIncome: 0.0, equity: 1.0, alternatives: 0.0 },
    },
    cadSplit: 0.5,
    usdSplit: 0.5,
    holdings: [
      { name: "JP MORGAN US BOND ACTIVE ETF", symbol: "JBND-T", currency: "CAD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "RBC US CORE PLUS BOND POOL", symbol: "RBF1083", currency: "USD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "ALPHABET", symbol: "GOOGL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FIDELITY GLOBAL INNOVATORS CLASS SERIES F", symbol: "FID5982-T", currency: "CAD", assetClass: "equity", weightInClass: 0.068182 },
      { name: "GE VERNOVA", symbol: "GEV", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ISHARES CORE S&P 500 INDEX ETF (CAD-HEDGED)", symbol: "XSP-T", currency: "CAD", assetClass: "equity", weightInClass: 0.128788 },
      { name: "ISHARES CORE S&P 500 INDEX ETF USD", symbol: "XUS.U", currency: "USD", assetClass: "equity", weightInClass: 0.196212 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF (CAD-HEDGED)", symbol: "XUH-T", currency: "CAD", assetClass: "equity", weightInClass: 0.212121 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF USD", symbol: "XUU.U", currency: "USD", assetClass: "equity", weightInClass: 0.158333 },
      { name: "ISHARES US SMALL CAP INDEX ETF (CAD-HEDGED)", symbol: "XSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "JPMORGAN CHASE", symbol: "JPM", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NORTHLAND POWER", symbol: "NPI-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "QUANTA SERVICES", symbol: "PWR", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TESLA", symbol: "TSLA", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TEXAS PACIFIC LAND", symbol: "TPL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "UBER", symbol: "UBER", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "US BANCORP", symbol: "USB", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "PURPOSE ENHANCED PREMIUM YIELD", symbol: "PAYF-T", currency: "CAD", assetClass: "alternative", weightInClass: 0.5 },
      { name: "WISDOMTREE EQUITY PREMIUM INCOME", symbol: "WTPI", currency: "USD", assetClass: "alternative", weightInClass: 0.5 },
    ],
  },
  {
    id: "deloitte",
    name: "Deloitte",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.14, equity: 0.83, alternatives: 0.03 },
      allEquity: { cash: 0.0, fixedIncome: 0.0, equity: 1.0, alternatives: 0.0 },
    },
    cadSplit: 0.5,
    usdSplit: 0.5,
    holdings: [
      { name: "JP MORGAN US BOND ACTIVE ETF", symbol: "JBND-T", currency: "CAD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "RBC US CORE PLUS BOND POOL", symbol: "RBF1083", currency: "USD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "ALPHABET", symbol: "GOOGL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "AMAZON", symbol: "AMZN", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CANADIAN NATIONAL RAILWAY", symbol: "CNR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CELESTICA", symbol: "CLS-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CONSTELLATION SOFTWARE", symbol: "CSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FUNDSTRAT GRANNY SHOTS US SMALL & MID-CAP ETF", symbol: "GRNJ", currency: "USD", assetClass: "equity", weightInClass: 0.05 },
      { name: "FIDELITY GLOBAL INNOVATORS CLASS SERIES F", symbol: "FID5982-T", currency: "CAD", assetClass: "equity", weightInClass: 0.068182 },
      { name: "ISHARES CORE S&P 500 INDEX ETF (CAD-HEDGED)", symbol: "XSP-T", currency: "CAD", assetClass: "equity", weightInClass: 0.083333 },
      { name: "ISHARES CORE S&P 500 INDEX ETF USD", symbol: "XUS.U", currency: "USD", assetClass: "equity", weightInClass: 0.143939 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF (CAD-HEDGED)", symbol: "XUH-T", currency: "CAD", assetClass: "equity", weightInClass: 0.166667 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF USD", symbol: "XUU.U", currency: "USD", assetClass: "equity", weightInClass: 0.106061 },
      { name: "ISHARES US SMALL CAP INDEX ETF (CAD-HEDGED)", symbol: "XSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "JPMORGAN CHASE", symbol: "JPM", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "GE VERNOVA", symbol: "GEV", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TEXAS PACIFIC LAND", symbol: "TPL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NORTHLAND POWER", symbol: "NPI-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NUTRIEN", symbol: "NTR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "QUANTA SERVICES", symbol: "PWR", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ECHOSTAR", symbol: "SATS", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TESLA", symbol: "TSLA", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TOURMALINE OIL", symbol: "TOU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "UBER", symbol: "UBER", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ONEOK", symbol: "OKE", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "US BANCORP", symbol: "USB", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "DYNAMIC PREMIUM YIELD PLUS", symbol: "DYN3361-T", currency: "CAD", assetClass: "alternative", weightInClass: 0.5 },
      { name: "DYNAMIC PREMIUM YIELD PLUS USD", symbol: "DYN3366", currency: "USD", assetClass: "alternative", weightInClass: 0.5 },
    ],
  },
  {
    id: "rcgt",
    name: "RCGT",
    profiles: {
      balanced: { cash: 0.0, fixedIncome: 0.28, equity: 0.66, alternatives: 0.06 },
      growth: { cash: 0.0, fixedIncome: 0.14, equity: 0.83, alternatives: 0.03 },
      allEquity: { cash: 0.0, fixedIncome: 0.0, equity: 1.0, alternatives: 0.0 },
    },
    cadSplit: 0.5,
    usdSplit: 0.5,
    holdings: [
      { name: "JP MORGAN US BOND ACTIVE ETF", symbol: "JBND-T", currency: "CAD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "RBC US CORE PLUS BOND POOL", symbol: "RBF1083", currency: "USD", assetClass: "fixedIncome", weightInClass: 0.5 },
      { name: "ALPHABET", symbol: "GOOGL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "AMAZON", symbol: "AMZN", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ARC RESOURCES", symbol: "ARX-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CANADIAN NATIONAL RAILWAY", symbol: "CNR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CELESTICA", symbol: "CLS-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "CONSTELLATION SOFTWARE", symbol: "CSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ECHOSTAR", symbol: "SATS", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "FIDELITY GLOBAL INNOVATORS CLASS SERIES F", symbol: "FID5982-T", currency: "CAD", assetClass: "equity", weightInClass: 0.068182 },
      { name: "FUNDSTRAT GRANNY SHOTS US SMALL & MID-CAP ETF", symbol: "GRNJ", currency: "USD", assetClass: "equity", weightInClass: 0.05 },
      { name: "GE VERNOVA", symbol: "GEV", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ISHARES CORE S&P 500 INDEX ETF (CAD-HEDGED)", symbol: "XSP-T", currency: "CAD", assetClass: "equity", weightInClass: 0.083333 },
      { name: "ISHARES CORE S&P 500 INDEX ETF USD", symbol: "XUS.U", currency: "USD", assetClass: "equity", weightInClass: 0.143939 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF (CAD-HEDGED)", symbol: "XUH-T", currency: "CAD", assetClass: "equity", weightInClass: 0.166667 },
      { name: "ISHARES CORE S&P US TOTAL MARKET INDEX ETF USD", symbol: "XUU.U", currency: "USD", assetClass: "equity", weightInClass: 0.106061 },
      { name: "ISHARES US SMALL CAP INDEX ETF (CAD-HEDGED)", symbol: "XSU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.054545 },
      { name: "JPMORGAN CHASE", symbol: "JPM", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NORTHLAND POWER", symbol: "NPI-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "NUTRIEN", symbol: "NTR-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "ONEOK", symbol: "OKE", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "QUANTA SERVICES", symbol: "PWR", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TESLA", symbol: "TSLA", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TEXAS PACIFIC LAND", symbol: "TPL", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "TOURMALINE OIL", symbol: "TOU-T", currency: "CAD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "UBER", symbol: "UBER", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "US BANCORP", symbol: "USB", currency: "USD", assetClass: "equity", weightInClass: 0.018182 },
      { name: "DYNAMIC PREMIUM YIELD PLUS", symbol: "DYN3361-T", currency: "CAD", assetClass: "alternative", weightInClass: 0.5 },
      { name: "DYNAMIC PREMIUM YIELD PLUS USD", symbol: "DYN3366", currency: "USD", assetClass: "alternative", weightInClass: 0.5 },
    ],
  },
];
