/**
 * Daily summary — the deterministic layer under the Brief page.
 *
 * One typed object, assembled from caches and small read-only pulls, with NO
 * Anthropic spend, so the page paints from data on every load. The AI
 * narrative (pm:brief) is read here only for its structured calls; it keeps
 * being generated by /api/morning-brief on its own schedule.
 *
 * Every section is built with allSettled — a failing source degrades to
 * `null` + an entry in `errors`, never a blank page.
 */

import { easternToday, easternLongDate } from "@/app/lib/date-eastern";
import { getRedis } from "@/app/lib/redis";
import type { MorningBrief } from "@/app/lib/types";
import { getMarketDrivers, type MarketDrivers } from "@/app/lib/market-drivers";
import { buildPerformanceSection, type PerformanceSection } from "./performance";
import { buildCalendarSection, type CalendarSection } from "./calendar";
import { buildBriefDigest, type BriefDigest } from "./hedging";
import { buildActionsSection, type ActionsSection } from "./actions";
import { type InflowSection } from "./inflow";
import { buildBookSections, type BookSection, type JournalSection, type FunnelSection } from "./book";
import { buildRegimeSection, type RegimeSection } from "./regime";

export type ChangedSection = {
  regime: { prev: string | null; now: string | null; changed: boolean; pending: { label: string; days: number; needed: number } | null };
  hedging: { prev: string | null; now: string | null; changed: boolean };
  cash: { prev: string | null; now: string | null; prevScore: number | null; nowScore: number | null; changed: boolean };
  alphaSpread1d: number | null;
  newTrips: number;
  newlyReady: string[];
  briefIsToday: boolean;
};

export type DailySummary = {
  generatedAt: string;
  today: string;
  todayLabel: string;
  performance: PerformanceSection | null;
  regime: RegimeSection | null;
  brief: BriefDigest | null;
  calendar: CalendarSection | null;
  drivers: MarketDrivers | null;
  actions: ActionsSection | null;
  inflow: InflowSection | null;
  book: BookSection | null;
  journal: JournalSection | null;
  funnel: FunnelSection | null;
  changed: ChangedSection | null;
  errors: { section: string; error: string }[];
  timingMs: Record<string, number>;
};

async function timed<T>(label: string, fn: () => Promise<T>, timing: Record<string, number>): Promise<T> {
  const t0 = Date.now();
  try {
    return await fn();
  } finally {
    timing[label] = Date.now() - t0;
  }
}

async function readBrief(): Promise<MorningBrief | null> {
  try {
    const raw = await (await getRedis()).get("pm:brief");
    return raw ? (JSON.parse(raw) as MorningBrief) : null;
  } catch {
    return null;
  }
}

export async function buildDailySummary(opts: { refreshDrivers?: boolean } = {}): Promise<DailySummary> {
  const today = easternToday();
  const timing: Record<string, number> = {};
  const errors: DailySummary["errors"] = [];

  const brief = await readBrief();

  const settle = async <T,>(section: string, p: Promise<T>): Promise<T | null> => {
    try {
      return await p;
    } catch (e) {
      errors.push({ section, error: e instanceof Error ? e.message : String(e) });
      return null;
    }
  };

  // Drivers first (regime's sector map joins on its ETF rows), everything else
  // in parallel with it.
  const driversP = settle("drivers", timed("drivers", () => getMarketDrivers({ refresh: opts.refreshDrivers }), timing));
  const [performance, calendar, digest, actions, books, drivers] = await Promise.all([
    settle("performance", timed("performance", buildPerformanceSection, timing)),
    settle("calendar", timed("calendar", () => buildCalendarSection(14), timing)),
    settle("brief", timed("brief", buildBriefDigest, timing)),
    settle("actions", timed("actions", () => buildActionsSection(brief), timing)),
    settle("book", timed("book", buildBookSections, timing)),
    driversP,
  ]);
  const regime = await settle("regime", timed("regime", () => buildRegimeSection(drivers), timing));

  // ── What changed since the previous session ──
  let changed: ChangedSection | null = null;
  try {
    const hist = regime?.history ?? [];
    const prevRow = hist.length >= 2 ? hist[hist.length - 2] : null;
    const nowLabel = regime?.composite?.label ?? null;
    const prevLabel = prevRow?.label ?? null;
    const briefDay = (digest?.date ?? digest?.generatedAt ?? "").slice(0, 10);
    const nowHedge = digest?.hedging.call?.action ?? null;
    const prevHedge = digest?.hedging.priorCall ?? null;
    const nowCash = digest?.cash.call?.action ?? null;
    const prevCash = digest?.cash.priorAction ?? null;
    const trips = actions?.thesis.tripped ?? [];
    const yesterday = new Date(Date.parse(`${today}T00:00:00Z`) - 86_400_000).toISOString().slice(0, 10);
    const newTrips = trips.reduce((n, t) => n + t.conditions.filter((c) => c.trippedAt && c.trippedAt.slice(0, 10) >= yesterday).length, 0);
    changed = {
      regime: { prev: prevLabel, now: nowLabel, changed: Boolean(prevLabel && nowLabel && prevLabel !== nowLabel), pending: regime?.composite?.pending ?? null },
      hedging: { prev: prevHedge, now: nowHedge, changed: Boolean(prevHedge && nowHedge && prevHedge !== nowHedge) },
      cash: {
        prev: prevCash,
        now: nowCash,
        prevScore: digest?.cash.priorScore ?? null,
        nowScore: digest?.cash.call?.score ?? null,
        changed: Boolean(prevCash && nowCash && prevCash !== nowCash),
      },
      alphaSpread1d: performance?.alphaCore.spread["1d"] ?? null,
      newTrips,
      newlyReady: books?.funnel.newlyReady ?? [],
      briefIsToday: briefDay === today,
    };
  } catch (e) {
    errors.push({ section: "changed", error: e instanceof Error ? e.message : String(e) });
  }

  return {
    generatedAt: new Date().toISOString(),
    today,
    todayLabel: easternLongDate(),
    performance,
    regime,
    brief: digest,
    calendar,
    drivers,
    actions,
    // The Desk zone was removed from the Brief, so nothing renders inflow —
    // don't pay for its Redis reads (analyst reports + street takeaways +
    // score history). The field stays on the type so re-adding is a one-liner.
    inflow: null,
    book: books?.book ?? null,
    journal: books?.journal ?? null,
    funnel: books?.funnel ?? null,
    changed,
    errors,
    timingMs: timing,
  };
}
